### ISSUE TITLE
Not copying subdirectories

### ISSUE THREAD

**Issue by bgoewert** [BGogurt/CopyUserFiles#11]
**Describe the bug**
The script is not copying sub-directories that are inside the defined folders.
- OS: Windows 7 & 10
- Version: 2.0.0
- Commit: 

**To Reproduce**
1. Run it on any machine using any method

**Expected behavior**
Copy everything correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/15313658/60370053-262e1880-99bb-11e9-9c86-3797fe52594b.png)

**Comment by garrettsummerfi3ld** [comment]
Commit 42f6a0477f0df11ee9504492d492a586078c31a2 addresses this, but this needs more testing.

Initial testing has been proven successful.

**Comment by bgoewert** [comment]
The script works if the destination directory does not already exist.
f7c109bec391dade99e4d7491ffd5e09a998b7fe

**Comment by garrettsummerfi3ld** [comment]
Commit 7e4c2a5cc0d66568b974a406434332b910face1d addresses and fixes issue.

Closing.
