### ISSUE TITLE
Require executable to be run as admin

### ISSUE THREAD

**Issue by bgoewert** [BGogurt/CopyUserFiles#9]
# Bug Report
The user profile folders required administrator access before files could be copied.

## Expected Behavior

> What behavior was supposed to happen?

Copy user files without error but not output anything.

## Actual Behavior

> What behavior *really* happened

Nothing. Pressing the button did not create a folder in the destination.

## Steps to Reproduce the Problem

1. Build exe
1. Copy exe to pc to copy from
1. Don't log in to Active Directory
1. Enter name of profile folder top copy from
1. Enter destination
1. Start script

## Specifications

- Version: 1.3.0
- Platform: Win 7
- Commit: Dev - c86ec77d9766ede7eb79d4b1eb57fbfc970c5797

**Comment by garrettsummerfi3ld** [comment]
Commit 8da4089a95820f7d68d17641777bc6d5d26dba90 has the beginnings of the feature. Its not functional but the groundwork is there

**Comment by bgoewert** [comment]
Fixed by adding an "An"

Reference commit https://github.com/BGogurt/CopyUserFiles/commit/0fb8450da05184ea98cf0f67b9a61573fa0b6751

**Comment by garrettsummerfi3ld** [comment]
You're kidding
